### ISSUE TITLE
启动就闪退

### ISSUE THREAD

**Issue by DengChaoZhong** [54fanqie/dingtalk-open#1]
项目运行就闪退了

2021-02-07 21:34:19.922062-0800 dingtalk-open[30736:18459015] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<ViewController 0x13df06c40> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key dateLab.'
*** First throw call stack:
(0x1a0fe99d4 0x1b499ab54 0x1a0efa6d4 0x1a21a4ca8 0x1a3183964 0x1a3494394 0x1a0ed4288 0x1a3490358 0x1a318b078 0x1a318b404 0x1a318bad8 0x1a388a814 0x1a388a028 0x1a388aebc 0x1a389bb14 0x1a384a428 0x1a385028c 0x1a2f26d48 0x1a344f5ec 0x1a2f27830 0x1a2f27338 0x1a2f2765c 0x1a2f26f18 0x1a2f2ebc4 0x1a3368a2c 0x1a3466d14 0x1a2f2e8b8 0x1a2d6de84 0x1a2d6c924 0x1a2d6dad0 0x1a384e464 0x1a338f320 0x1af97f7c4 0x1af9a71f0 0x1af98cf20 0x1af9a6f04 0x102965528 0x1029689f0 0x1af9cbf20 0x1af9cbbe8 0x1af9cc0bc 0x1a0f69be0 0x1a0f69ae0 0x1a0f68e28 0x1a0f633d0 0x1a0f62b90 0x1b7285598 0x1a384c638 0x1a3851bb8 0x10289ade4 0x1a0c41588)
libc++abi.dylib: terminating with uncaught exception of type NSException
/System/Library/PrivateFrameworks/CoreServicesInternal.framework/CoreServicesInternal
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<ViewController 0x13df06c40> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key dateLab.'
terminating with uncaught exception of type NSException

删除dateLab关联就好了

**Comment by 54fanqie** [comment]
跟新了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2021年2月8日(星期一) 中午1:34
收件人: "54fanqie/dingtalk-open"<dingtalk-open@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [54fanqie/dingtalk-open] 启动就闪退 (#1)





 
项目运行就闪退了
 
2021-02-07 21:34:19.922062-0800 dingtalk-open[30736:18459015] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<ViewController 0x13df06c40&gt; setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key dateLab.'
 *** First throw call stack:
 (0x1a0fe99d4 0x1b499ab54 0x1a0efa6d4 0x1a21a4ca8 0x1a3183964 0x1a3494394 0x1a0ed4288 0x1a3490358 0x1a318b078 0x1a318b404 0x1a318bad8 0x1a388a814 0x1a388a028 0x1a388aebc 0x1a389bb14 0x1a384a428 0x1a385028c 0x1a2f26d48 0x1a344f5ec 0x1a2f27830 0x1a2f27338 0x1a2f2765c 0x1a2f26f18 0x1a2f2ebc4 0x1a3368a2c 0x1a3466d14 0x1a2f2e8b8 0x1a2d6de84 0x1a2d6c924 0x1a2d6dad0 0x1a384e464 0x1a338f320 0x1af97f7c4 0x1af9a71f0 0x1af98cf20 0x1af9a6f04 0x102965528 0x1029689f0 0x1af9cbf20 0x1af9cbbe8 0x1af9cc0bc 0x1a0f69be0 0x1a0f69ae0 0x1a0f68e28 0x1a0f633d0 0x1a0f62b90 0x1b7285598 0x1a384c638 0x1a3851bb8 0x10289ade4 0x1a0c41588)
 libc++abi.dylib: terminating with uncaught exception of type NSException
 /System/Library/PrivateFrameworks/CoreServicesInternal.framework/CoreServicesInternal
 *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<ViewController 0x13df06c40&gt; setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key dateLab.'
 terminating with uncaught exception of type NSException
